# Generated by Django 4.1.3 on 2022-11-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('finished', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=100)),
                ('priority', models.CharField(choices=[('H', 'Alta'), ('N', 'Normal'), ('L', 'Baja')], default='N', max_length=1)),
                ('due_date', models.DateField(blank=True)),
            ],
        ),
    ]
