# Generated by Django 4.1.3 on 2022-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('blue', 'azul'), ('red', 'rojo'), ('orange', 'naranja'), ('green', 'verde')], default='blue', max_length=6),
        ),
    ]
